name: OpenCode Auth Restore
description: 'Set up OpenCode with Antigravity Auth in GitHub Actions/Copilot'
branding:
  icon: 'lock'
  color: 'blue'

inputs:
  bundle:
    description: 'Base64-encoded auth bundle (from secrets.OPENCODE_AUTH_BUNDLE)'
    required: true
  install:
    description: 'Whether to install opencode-ai and plugins'
    required: false
    default: 'true'
  headless:
    description: 'Set OPENCODE_HEADLESS=1 env var'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Install OpenCode
      if: inputs.install == 'true'
      shell: bash
      run: |
        npm install -g opencode-ai opencode-antigravity-auth@1.2.8

    - name: Restore Auth
      shell: bash
      run: |
        mkdir -p ~/.config/opencode ~/.local/share/opencode /tmp/opencode-restore
        
        # Decode and extract
        echo "${{ inputs.bundle }}" | base64 -d | tar -xzf - -C /tmp/opencode-restore
        
        # Manifest check
        if [ ! -f /tmp/opencode-restore/manifest.json ]; then
          echo "❌ Invalid bundle: missing manifest.json"
          exit 1
        fi
        
        # Restore files
        if [ -d /tmp/opencode-restore/config/opencode ]; then
          cp -r /tmp/opencode-restore/config/opencode/* ~/.config/opencode/
        fi
        
        if [ -d /tmp/opencode-restore/data/opencode ]; then
          cp -r /tmp/opencode-restore/data/opencode/* ~/.local/share/opencode/
        fi
        
        # Cleanup
        rm -rf /tmp/opencode-restore
        
        echo "✅ OpenCode auth restored"

    - name: Set Headless
      if: inputs.headless == 'true'
      shell: bash
      run: echo "OPENCODE_HEADLESS=1" >> $GITHUB_ENV
