# OpenCode Agent Dispatcher
# Runs OpenCode commands via workflow_dispatch or schedule.
# Commands are defined in .opencode/command/*.md files.
# Install with: bunx opencode-sync install --workflows --commands

name: OpenCode Agent

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Command to run'
        required: true
        type: choice
        options:
          - project-review
          - issue-triage
          - issue-discover
          - issue-organize
          - manage-issues
      arguments:
        description: 'Additional arguments for the command'
        required: false
        type: string

  schedule:
    - cron: '0 9 * * 1'
    - cron: '0 9 1 * *'

env:
  REPO: ${{ github.repository }}

jobs:
  agent:
    runs-on: ubuntu-latest
    environment: copilot
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2

      - name: Restore OpenCode Auth
        uses: rothnic/opencode-sync@v1
        with:
          bundle: ${{ secrets.OPENCODE_AUTH_BUNDLE }}

      - name: Configure Git
        run: |
          git config --global user.name "OpenCode Agent"
          git config --global user.email "agent@opencode.ai"

      - name: Determine command
        id: cmd
        run: |
          if [ "${{ github.event_name }}" = "schedule" ]; then
            DAY=$(date -u +%d)
            if [ "$DAY" = "01" ]; then
              echo "command=project-review" >> $GITHUB_OUTPUT
            else
              echo "command=issue-triage" >> $GITHUB_OUTPUT
            fi
          else
            echo "command=${{ inputs.command }}" >> $GITHUB_OUTPUT
          fi
          echo "arguments=${{ inputs.arguments }}" >> $GITHUB_OUTPUT

      - name: Run OpenCode command
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          opencode run --command "${{ steps.cmd.outputs.command }}" "${{ steps.cmd.outputs.arguments }}"

      - name: Post workflow summary
        if: always()
        run: |
          echo "## OpenCode Agent Run" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Command:** ${{ steps.cmd.outputs.command }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Arguments:** ${{ steps.cmd.outputs.arguments || 'none' }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Status:** ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
