# @opencode Mention Handler
# Triggers when @opencode is mentioned in issue/PR comments.
# Uses the mention-handler command from .opencode/command/.
# Install with: bunx opencode-sync install --workflows --commands

name: OpenCode Mention Handler

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  handle-mention:
    runs-on: ubuntu-latest
    environment: copilot
    if: |
      contains(github.event.comment.body, '@opencode') &&
      !github.event.comment.user.bot
    
    steps:
      - name: Acknowledge mention
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: 'eyes'
            });

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.issue.pull_request.head.ref || github.ref }}
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2

      - name: Restore OpenCode Auth
        uses: rothnic/opencode-sync@v1
        with:
          bundle: ${{ secrets.OPENCODE_AUTH_BUNDLE }}

      - name: Configure Git
        run: |
          git config --global user.name "OpenCode Agent"
          git config --global user.email "agent@opencode.ai"

      - name: Extract prompt from mention
        id: prompt
        run: |
          COMMENT='${{ github.event.comment.body }}'
          PROMPT=$(echo "$COMMENT" | sed 's/.*@opencode[[:space:]]*//')
          echo "prompt<<EOF" >> $GITHUB_OUTPUT
          echo "$PROMPT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Run mention handler
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
          TRIGGER_COMMENT_URL: ${{ github.event.comment.html_url }}
          TRIGGER_USER: ${{ github.event.comment.user.login }}
          IS_PR: ${{ github.event.issue.pull_request != null }}
        run: |
          opencode run --command "mention-handler" "${{ steps.prompt.outputs.prompt }}"

      - name: Post completion reaction
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: 'rocket'
            });

      - name: Post failure reaction
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: 'confused'
            });
